#Docker Work na BSDK

name: Ultroid Workflow

on:
    push:
    workflow_dispatch:
    
env:
 GitHubMail: "error@notavailable.live"
 GitHubName: "ProgrammingError"
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${GitHubName}
           git config --global user.email ${GitHubMail}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.CREDS }} ultroid
       - name: Running Ultroid
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd ultroid
           wget https://raw.githubusercontent.com/TeamUltroid/Ultroid/dev/Dockerfile
           echo "CMD bash resources/startup/startup.sh" >> Dockerfile
           docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t ultroid
           docker run --privileged --env-file .env --rm -i ultroid
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://${{ secrets.GHTOKEN }}@github.com/ProgrammingError/ultroid-wf loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
